app/main/forms.py
# main蓝图，表单

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo
from flask_login import current_user


class EditProfileForm(FlaskForm):
    """
    修改个人资料表单
    """
    username = StringField('用户名：', validators=[DataRequired(), Length(1, 64)])
    info = TextAreaField('个人简介：')
    submit = SubmitField('提交')


class EditPasswordForm(FlaskForm):
    """
    修改密码表单
    """
    old_pwd = StringField('旧密码:', validators=[DataRequired()])
    new_pwd = PasswordField('新密码:', validators=[DataRequired(),
                                             EqualTo('new_pwd2', message='两次密码必须一致！')])
    new_pwd2 = PasswordField('新密码：', validators=[DataRequired()])
    submit = SubmitField('确认修改')

    def validate_old_pwd(self, field):
        if not current_user.verify_password(field.data):
            raise ValidationError('旧密码输入错误！')


class CommentForm(FlaskForm):
    """
    评论电影表单
    """
    body = TextAreaField('想对这个电影说点什么？', validators=[DataRequired()])
    submit = SubmitField('提交评论')

app/main/__init__.py
# 注册main蓝本

from flask import Blueprint
from app.models import Permission


main = Blueprint('main', __name__)


# 将models.py中的Permission类加入全局变量中，这样模板中可以访问
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


from . import views, errors

app/main/views.py
from . import main
from app import db
from flask import render_template, request, current_app, abort, flash, url_for, redirect, session
from app.models import Movie, Tag, User, Permission, Comment, Userlog, Moviecol
from flask_login import login_required, current_user
from .forms import EditProfileForm, EditPasswordForm, CommentForm
from datetime import datetime
from sqlalchemy import and_, or_
from app.decorators import permission_required, admin_required


@main.route('/')
def index():
    """显示首页"""
    movies = {}
    tags = Tag.query.all()
    tag_dict = {}
    for tag in tags:
        # print(tag)
        tag_dict[tag.name] = tag.name
        movies[tag.name] = tag.movies.order_by(Movie.addtime.desc()).limit(15).all()
    # print(movies)

    movies['recomment_movies'] = Movie.query.filter_by(is_recomment=True).order_by(Movie.release_time.desc()).limit(5).all()

    # 按标签电影排名前10
    rank_movies = {}
    for key, value in tag_dict.items():
        rank_movies[value] = Tag.query.filter(Tag.name == value).first().movies.order_by(Movie.rating.desc()).limit(20).all()

    return render_template('main/index.html',
                           movies=movies,
                           rank_movies=rank_movies)


@main.route('/show/all/movies')
def show_all_movies():
    """显示所有电影"""
    p = {}
    p['area'] = request.args.get('area', '')
    p['time'] = request.args.get('time', '')
    p['tag'] = request.args.get('tag', '')

    # 全部电影分页
    page = request.args.get('page', 1, type=int)
    if p['tag']:
        pagination = Tag.query.filter(Tag.name == p['tag']).first().movies.filter(
                and_(Movie.area.like('%{}%'.format(p['area'])), Movie.release_time.like('%{}%'.format(p['time'])))
            ).order_by(
                Movie.rating.desc()
            ).paginate(
                page,
                per_page=current_app.config.get('FLASK_MOVIE_PER_PAGE_COUNT'),
                error_out=True
            )
    else:
        pagination = Movie.query.filter(
                and_(Movie.area.like('%{}%'.format(p['area'])), Movie.release_time.like('%{}%'.format(p['time'])))
            ).order_by(
                Movie.rating.desc()
            ).paginate(
                page,
                per_page=current_app.config.get('FLASK_MOVIE_PER_PAGE_COUNT'),
                error_out=True
            )

    # 所有标签
    tags = Tag.query.all()

    # 地区
    areas = ['中国大陆', '香港', '美国', '台湾', '韩国', '日本', '印度', '英国', '德国', '俄罗斯', '苏联', '西班牙', '法国', '巴西']

    # 电影
    movies = pagination.items

    # 年代
    times = [str(i) for i in range(2018, 1989, -1)]

    return render_template('main/show-all-movies.html',
                           tags=tags,
                           areas=areas,
                           movies=movies,
                           pagination=pagination,
                           p=p,
                           times=times)


@main.route('/all/tags/')
def show_all_tags():
    """
    所有标签下的电影
    :return:
    """
    tags = Tag.query.order_by(Tag.addtime.desc()).all()
    # 全部电影分页
    page = request.args.get('page', 1, type=int)
    pagination = Movie.query.order_by(Movie.rating.desc()).paginate(
        page,
        per_page=current_app.config.get('FLASK_MOVIE_PER_PAGE_COUNT'),
        error_out=True
    )
    movies = pagination.items

    return render_template('main/show-all-tags.html',
                           tags=tags,
                           movies=movies,
                           pagination=pagination)


@main.route('/<tag>/movies/')
def show_tag_movies(tag):
    """
    标签下的电影
    :param tagname:
    :return:
    """
    tags = Tag.query.order_by(Tag.addtime.desc()).all()
    tag = Tag.query.filter(Tag.name == tag).first()
    page = request.args.get('page', 1, type=int)
    pagination = tag.movies.order_by(Movie.rating.desc()).paginate(
        page,
        per_page=current_app.config.get('FLASK_MOVIE_PER_PAGE_COUNT'),
        error_out=True
    )
    movies = pagination.items

    return render_template('main/show-tag-movies.html',
                           tag=tag,
                           tags=tags,
                           pagination=pagination,
                           movies=movies)


@main.route('/movie/<id>', methods=['POST', 'GET'])
def movie(id):
    """
    电影信息页面
    :param id:
    :return:
    """
    form = CommentForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated or not current_user.can(Permission.COMMENT):
            flash('您需要登录后才可以评论哦！')
            return redirect(url_for('auth.login'))
        comment = Comment(body=form.body.data,
                          movie_id=id,
                          user_id=current_user.id,
                          addtime=datetime.now())
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交,谢谢分享!')
        return redirect(url_for('main.movie', id=id))

    movie = Movie.query.get_or_404(id)
    page = request.args.get('page', 1, int)
    pagination = movie.comments.order_by(Comment.addtime.desc()).paginate(
        page,
       per_page=current_app.config['FLASK_COMMENT_PER_PAGE_COUNT'],
       error_out=True
    )
    comments = pagination.items
    tags = '/'.join([tag.name for tag in movie.tags.all()])
    return render_template('main/movie.html',
                           movie=movie,
                           tags=tags,
                           form=form,
                           comments=comments,
                           pagination=pagination)


@main.route('/movie/play/<id>', methods=['POST', 'GET'])
def play_movie(id):
    """
    播放电影
    :param id:
    :return:
    """
    form = CommentForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated or not current_user.can(Permission.COMMENT):
            flash('您需要登录后才可以评论哦！')
            return redirect(url_for('auth.login'))
        comment = Comment(body=form.body.data,
                          movie_id=id,
                          user_id=current_user.id,
                          addtime=datetime.now())
        db.session.add(comment)
        db.session.commit()
        flash('评论已提交,谢谢分享!')
        return redirect(url_for('main.play_movie', id=id))

    movie = Movie.query.get_or_404(id)
    # 增加一次播放次数
    movie.play_num += 1
    db.session.add(movie)
    db.session.commit()
    # 电影评论分页
    page = request.args.get('page', 1, int)
    pagination = movie.comments.order_by(Comment.addtime.desc()).paginate(
        page,
        per_page=current_app.config['FLASK_COMMENT_PER_PAGE_COUNT'],
        error_out=True
    )
    comments = pagination.items
    return render_template('main/play-movie.html',
                           movie=movie,
                           form=form,
                           comments=comments,
                           pagination=pagination)


@main.route('/movie/<int:id>/save-dm/')
@login_required
def save_dm(id):
    pass


@main.route('/movie/play/style.xml/')
def load_ckplayer_style_file():
    return render_template('main/style.xml')


@main.route('/movie/play/language.xml/')
def load_ckplayer_language_file():
    return render_template('main/language.xml')


@main.route('/crossdomain.xml/')
def load_ckplayer_crossdomain_file():
    return render_template('main/../../crossdomain.xml')


@main.route('/user/<id>/')
@login_required
def user(id):
    """
    显示用户信息
    :param username:
    :return:
    """
    user = User.query.filter_by(id=id).first()
    if not user:
        abort(404)

    # 电影日志
    userlog = user.userlogs.order_by(Userlog.log_time.desc())[1]
    moviecols = [moviecol.movie for moviecol in user.moviecols]

    # 所有的评论
    comments = current_user.comments

    # 关注的用户
    followeds = user.followed.all()
    # 关注你的用户
    followers = user.followers.all()

    return render_template('main/user.html',
                           user=user,
                           last_userlog=userlog,
                           moviecols=moviecols,
                           comments=comments,
                           followeds=followeds,
                           followers=followers)


@main.route('/user/<id>/editprofile/', methods=['GET', 'POST'])
@login_required
def edit_profile(id):
    """
    修改个人资料
    :param id:
    :return:
    """
    user = User.query.get_or_404(id)
    if current_user != user:
        flash('您没有权限修改他人资料!')
        return redirect(url_for('mian.user', id=id))
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.info = form.info.data
        try:
            db.session.add(current_user)
            db.session.commit()
        except:
            flash('修改失败，可能用户名被注册过！')
            db.session.rollback()
            return redirect(url_for('main.edit_profile', id=current_user.id))
        flash('资料修改成功！')
        return redirect(url_for('main.user', id=id))
    form.username.data = current_user.username
    form.info.data = current_user.info

    return render_template('main/edit-profile.html', form=form)


@main.route('/user/editpassword/', methods=['GET', 'POST'])
@login_required
def edit_password():
    """
    修改个人密码
    :return:
    """
    form = EditPasswordForm()
    if form.validate_on_submit():
        current_user.password = form.new_pwd.data
        db.session.add(current_user)
        db.session.commit()
        flash('密码重置完成！请牢记新密码！')
        return redirect(url_for('main.user', id=current_user.id))

    return render_template('main/edit-password.html', form=form)


@main.route('/moviecol/<int:id>')
@login_required
def movie_col(id):
    """
    电影收藏功能
    :param id: 电影id
    :return:
    """
    moviecol = Moviecol.query.filter_by(user_id=current_user.id).filter(Moviecol.movie_id==id).first()
    print(moviecol)
    if moviecol is not None:
        flash('您已经收藏过该电影了!')
        return redirect(url_for('main.movie', id=id))
    moviecol = Moviecol(addtime=datetime.now(),

app/templates/main/edit-password.html
{% extends 'base.html' %}

{% block content %}
<div class="container" style="margin-top:120px">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title text-center"><span class="glyphicon glyphicon-log-in"></span>&nbsp;修改密码</h3>
                </div>
                <div class="panel-body">
                    <!--注册表单-->
                    <form role="form" method="post">
                        <fieldset>
                            <div class="form-group">
                                <label for="input_contact"><span class="glyphicon glyphicon-lock"></span>&nbsp;请输入旧密码:</label>
                                {#表单错误提示#}
                                <div class="old-pwd">
                                    {{ form.old_pwd }}
                                </div>
                                {% for err in form.old_pwd.errors %}
                                    <div class="col-md-12">
                                        <p style="color: red">{{ err }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_contact"></div>
                            <div class="form-group">
                                <label for="input_contact"><span class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.new_pwd.label }}</label>
                                {#表单错误提示#}
                                <div class="new-pwd">
                                    {{ form.new_pwd}}
                                </div>

                                {% for err in form.new_pwd.errors %}
                                    <div class="col-md-12">
                                        <p style="color: red">{{ err }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_contact"></div>
                            <div class="form-group">
                                <label for="input_password"><span
                                        class="glyphicon glyphicon-lock"></span>&nbsp;{{ form.new_pwd2.label }}</label>
                                <div class="new-pwd2">
                                    {{ form.new_pwd2}}
                                </div>
                                {#表单错误提示#}
                                {% for err in form.new_pwd2.errors %}
                                    <div class="col-md-12">
                                        <p style="color: red">{{ err }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_password"></div>
                            <div class="submit">
                                {{ form.csrf_token }}
                                {{ form.submit }}
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/edit-profile.html
{% extends 'base.html' %}

{% block content %}
   <div class="container" style="margin-top:120px">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-log-in"></span>&nbsp;修改资料</h3>
                </div>
                <div class="panel-body">
                    <!--注册表单-->
                    <form role="form" method="post">
                        <fieldset>
                            <div class="form-group">
                                <label for="input_contact"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ form.username.label }}</label>
                                {#表单错误提示#}
                                <div class="email">
                                    {{ form.username}}
                                </div>
                                {% for err in form.username.errors %}
                                    <div class="col-md-12">
                                        <p style="color: red">{{ err }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_contact"></div>
                            <div class="form-group">
                                <label for="input_contact"><span class="glyphicon glyphicon-user"></span>&nbsp;{{ form.info.label }}</label>
                                {#表单错误提示#}
                                <div class="username">
                                    {{ form.info}}
                                </div>

                                {% for err in form.info.errors %}
                                    <div class="col-md-12">
                                        <p style="color: red">{{ err }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-md-12" id="error_contact"></div>

                            <div class="submit">
                                {{ form.csrf_token }}
                                {{ form.submit }}
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}


{% block title %}随风飘电影首页{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/index.css') }}" type="text/css">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div id="myCarousel" class="carousel slide">

                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    {% for recomment_movie in movies['recomment_movies'] %}
                        {% if recomment_movie == movies['recomment_movies'][0] %}
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        {% else %}
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                        {% endif %}
                    {% endfor %}
                </ol>

                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner recomment-movie-img">
                    {% for movie in movies['recomment_movies'] %}
                        {% if movie == movies['recomment_movies'][0] %}
                            <div class="item active">
                                <a href="{{ url_for('main.movie', id=movie.id) }}?recomment_movie=true"><img src="{{ movie.cover }}" alt="First slide" style="height: 500px; width:100%"></a>
                            </div>
                        {% else %}
                            <div class="item">
                                <a href="{{ url_for('main.movie', id=movie.id) }}?recomment_movie=true"><img src="{{ movie.cover }}" alt="First slide" style="height: 500px; width: 100%"></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <!-- 轮播（Carousel）导航 -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>

{#    电影页#}
    <div class="container">
        {% for key, movie_list in movies.items() %}
            <hr>
            {% if key == 'recomment_movies' %}
                <p></p>
            {% else %}
            <div class="row movie-tag">
                <div class="col-xs-9 col-sm-5 col-md-6 type">
                    <p><strong>{{ key }}电影</strong></p>
                </div>
                <div class="col-xs-3 col-sm-3 col-md-3 more">
                    <a href="{{ url_for('main.show_all_movies') }}?tag={{ key }}" class="text-center">
                    <p><strong>更多</strong></p>
                    </a>
                </div>
                <div class="rank col-sm-4 col-md-3 hidden-xs text-center">
                    <p><strong>{{ key }} | rating排名</strong></p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-8 col-xs-12 movie-list">
                    {% for movie in movie_list %}
                        {% if movie == movie_list[0] %}
                        <div class="col-md-4 col-sm-3 col-xs-3">
                            <div class="first thumbnail">
                                <a href="{{ url_for('main.movie', id=movie.id) }}">
                                    <img src="{{ movie.cover }}" alt="">
                                </a>
                                <a href="{{ url_for('main.movie', id=movie.id) }}" class="first-info">
                                    <p>{{ movie.name }} &nbsp <strong>{{ movie.rating }}</strong></p>
                                    <p>演员:{{ movie.actors }}</p>
                                </a>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-md-2 col-sm-3 col-xs-3">
                            <div class="secend thumbnail">
                                <a href="{{ url_for('main.movie', id=movie.id) }}">
                                    <img src="{{ movie.cover }}" alt="">
                                    <p class="text-center secend-info">{{ movie.name }} &nbsp <strong>{{ movie.rating }}</strong></p>
                                </a>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>

{#                右侧电影排行#}
                <div class="col-sm-4 hidden-xs">
                    <ol class="movie-rank">
                        {% for movie in rank_movies[key] %}
                            <li class="col-sm-10 text-left"><a href="{{ url_for('main.movie', id=movie.id) }}">{{ movie.name }}</a></li>
                            <a href="#" class="col-sm-2 text-right">{{ movie.rating }}</a>
                        {% endfor %}
                    </ol>
                </div>

            </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

app/templates/main/movie.html
{% extends 'base.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/movie.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 movie-cover thumbnail">
                <a href="{{ movie.cover }}"><img src="{{ movie.cover }}" alt=""></a>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 movie-info">
                <div class="text-left">
                    <p>{{ movie.name }}</p>
                </div>
                <br>
                <ul class="text-left" id="info">
                    <li>
                        <span class="pl">导演:</span>
                        <a href="#">{{ movie.director }}</a>
                    </li>
                    <li>
                        <span class="pl">主演：</span>
                        <a href="#">{{ movie.actors[:100] }}······</a>
                    </li>
                    <li>
                        <span class="pl">类型：</span>
                        <a href="#">{{ tags }}</a>
                    </li>
                    <li>
                        <span class="pl">豆瓣评分：</span>
                        <a href="#"><strong>{{ movie.rating}}</strong></a>
                    </li>
                    <li>
                        <span class="pl">上映地区：</span>
                        <a href="#">{{ movie.area }}</a>
                    </li>
                    <li>
                        <span class="pl">上映时间：</span>
                        <a href="#">{{ movie.release_time }}</a>
                    </li>
                    <li>
                        <span class="pl">播放次数：</span>
                        <a href="#">{{ movie.play_num}}</a>
                    </li>
                    <br>
                    <div class="row btn">
                        <a href="{{ url_for('main.play_movie', id=movie.id) }}">
                            <button type="button" class="btn btn-primary"
                                    data-loading-text="Loading...">立即观看
                            </button>
                        </a>
                        <a href="{{ url_for('main.movie_col', id=movie.id) }}" id="moviecol">
                            <button type="button" class="btn btn-primary"
                                    data-loading-text="Loading...">加入收藏
                            </button>
                        </a>
                    </div>
                </ul>
            </div>
        </div>
        &nbsp;
        <hr>
{#        电影剧情简介#}
        <div class="row movie-introdction">
            <h4 style="color: #55ff2d;">{{ movie.name }}的剧情简介:</h4>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;{{ movie.introduction }}</p>
        </div>
        &nbsp
        <hr>
{#        评论#}
        {% include '_comment.html' %}
    </div>

{% endblock %}

app/templates/main/play-movie.html
{% extends 'base.html' %}

{% block title %}{{ movie.name }}{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/play-movie.css') }}">
{% endblock %}

{% block js %}
    {{ super() }}
{#    <script src="{{ url_for('static', filename='ext/js/search_movie.js') }}"></script>#}
    <script src="{{ url_for('static', filename='ext/js/search_movie.js') }}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row title text-center" id="movie-name">
        <h1>{{ movie.name }}</h1>
        <br>
    </div>
</div>

{#电影播放页面设置    #}
<script type="text/javascript" src="{{ url_for('static', filename='ckplayer/ckplayer/ckplayer.js') }}"></script>

<div class="container">
    <div class="row">
        <div class="col-md-9 col-sm-8 col-xs-12">
            <div id="video" class="play"></div>
            {#    弹幕#}
            <div class="dm">
                <input type="text" id="danmutext">
                <button type="button" onclick="newDanmu()">添加弹幕</button>
            </div>

    {#    电影简介及评论#}
            <div class="introduction">
                <p>{{ movie.name }}的剧情简介:</p>
                <p>&nbsp;&nbsp;&nbsp;&nbsp;{{ movie.introduction }}</p>
            </div>
            <hr>
    {#        评论#}
            <div class="comment">
                {% include '_comment.html' %}
            </div>
        </div>
        <div class="movie-source col-md-3 col-sm-4 col-xs-12" id="content">
            <div class="aside">

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
	var videoObject = {
		container: '#video',
		variable: 'player',
		flashplayer:true,
        loaded: 'loadedHandler',
        video:'{{ movie.url }}'
	};
	var player=new ckplayer(videoObject);

	function loadedHandler() {}

	function errorHandler() {
		alert('视频播放错误')
	}

	{#保存弹幕信息#}
    function saveDanmu(danmuText) {
        var xhr = new XMLHttpRequest();
        var url = '{{ url_for("main.save_dm", id=movie.id) }}';
        xhr.onreadystatechange=function()
        {
           if (xhr.readyState==4 && xhr.status==200)
           {
               document.getElementById('dm').appendChild('<p class="alert alert-success">弹幕发表成功!</p>')
           }
        };
        xhr.open('POST', url, true);
        xhr.send(danmuText);
    }

	var y = 0;
	var DArr = [];
	var YArr = [];
	function newDanmu() {
	    // 获取input标签内容
        var danmuText = document.getElementById('danmutext').value;
        //弹幕说明
        y+=20;
        if(y>300)y=0;
        var danmuObj = {
            list: [{
                type: 'image', //定义元素类型：只有二种类型，image=使用图片，text=文本
                file: '../material/logo.png', //图片地址
                radius: 30, //图片圆角弧度
                width: 30, //定义图片宽，必需要定义
                height: 30, //定义图片高，必需要定义
                alpha: 0.9, //图片透明度(0-1)
                marginLeft: 10, //图片离左边的距离
                marginRight: 10, //图片离右边的距离
                marginTop: 10, //图片离上边的距离
                marginBottom: 10, //图片离下边的距离
                clickEvent: "link->http://"
            }, {
                type: 'text', //说明是文本
                //text: '演示弹幕内容，弹幕只支持普通文本，不支持HTML', //文本内容
                text: danmuText,
                color: '#e4fffc', //文本颜色
                size: 16, //文本字体大小，单位：px
                font: '"Microsoft YaHei", YaHei, "微软雅黑", SimHei,"\5FAE\8F6F\96C5\9ED1", "黑体",Arial', //文本字体
                leading: 30, //文字行距
                alpha: 1, //文本透明度(0-1)
                paddingLeft: 10, //文本内左边距离
                paddingRight: 10, //文本内右边距离
                paddingTop: 0, //文本内上边的距离
                paddingBottom: 0, //文本内下边的距离
                marginLeft: 0, //文本离左边的距离
                marginRight: 10, //文本离右边的距离
                marginTop: 10, //文本离上边的距离
                marginBottom: 0, //文本离下边的距离
                backgroundColor: '#55ff2d', //文本的背景颜色
                backAlpha: 0.5, //文本的背景透明度(0-1)
                backRadius: 30, //文本的背景圆角弧度
                clickEvent: "actionScript->videoPlay"
            }],
            x: '100%', //x轴坐标
            y: y, //y轴坐标
            //position:[2,1,0],//位置[x轴对齐方式（0=左，1=中，2=右），y轴对齐方式（0=上，1=中，2=下），x轴偏移量（不填写或null则自动判断，第一个值为0=紧贴左边，1=中间对齐，2=贴合右边），y轴偏移量（不填写或null则自动判断，0=紧贴上方，1=中间对齐，2=紧贴下方）]
            alpha: 1,
            //backgroundColor:'#FFFFFF',
            backAlpha: 0.8,
            backRadius: 30 //背景圆角弧度
        };
        var danmu = player.addElement(danmuObj);
        var danmuS = player.getElement(danmu);
        var obj = {
            element: danmu,
            parameter: 'x',
            static: true, //是否禁止其它属性，true=是，即当x(y)(alpha)变化时，y(x)(x,y)在播放器尺寸变化时不允许变化
            effect: 'None.easeOut',
            start: null,
            //end: -danmuS['width']+300,
            end: -danmuS['width'],
            speed: 15,
            overStop: true,
            pauseStop: true,
            callBack: 'deleteChild'
        };
        var danmuAnimate = player.animate(obj);
        DArr.push(danmuAnimate);
        console.log(danmu);
        YArr.push(danmu);
    }

    function deleteChild(ele) {
        if(player) {
            player.deleteElement(ele);
            if(YArr.indexOf(ele)>-1){//在YArr也就是保存弹幕的全局变量里搜索该弹幕，然后删除
                var n=YArr.indexOf(ele);
                console.log(n);
                YArr.splice(n,1);
            }
        }
    }

</script>

{% endblock %}

app/templates/main/show-all-movies.html
{% extends 'base.html' %}
{% import '_macros.html' as macro %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='main/css/show-all-movies.css') }}">
{% endblock %}

{% block content %}
{#    加入筛选标签#}
{% include '_tags2.html' %}

<div class="container">
    <div class="row movie-list">
        {% for movie in movies %}
            {% include '_movie-list.html' %}
        {% endfor %}
    </div>
    <hr>
    <div class="row text-center page">
        {#定义分页#}
        {{ macro.pagination_widget(pagination, 'main.show_all_movies', time=p['time'], area=p['area'], tag=p['tag']) }}
    </div>
</div>
{% endblock %}